# Generated by Django 2.2.2 on 2019-06-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_avi',
            field=models.BooleanField(default=False),
        ),
    ]
